language: php
php:
  - '7.1'

before_install:
  -  apt-get install php-pear php5-dev
  - apt-get install libcurl3-openssl-dev
  - pecl install cassandra

install:
  - composer install

script: make test